### ISSUE TITLE
wymiwyg-commons-core don't include the license file

### ISSUE THREAD

**Issue by puntogil** [retog/wymiwyg-commons-core#1]
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
thanks
regards

**Comment by retog** [comment]
The POM says it is apache 2 licensed. Will add file.
